logc_logError.3